### ISSUE TITLE
Remove Idle timeouts

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/warden#101]
The concerns for this issue are:

* Idle timeout is not safe for clients.
* The timeout occurs while a client is attepting to call.
* It is also not thread safe.

The original PR can be found [here](https://github.com/cloudfoundry/warden/pull/93).

The PR has been reverted a second time at Warden [commit](https://github.com/cloudfoundry/warden/commit/9c9f70be01fa109a40f4c7fd63f8792dc9fedda8) and the corresponding DEA [commit]( https://github.com/cloudfoundry/dea_ng/commit/db3de2ad2be939475a0c80d3c940efef1a44dd9a).

The reason we reverted the commits is due to the fact that DEA's started to crash after a couple of hours under load. The root problem seems to be that connections between the DEA and Warden are not being properly closed and the DEA relied on the timeout connections to clean things up. We believe a better solution is to go through and make sure that all of the connections that are created between these components are correctly receiving a close connection call.

Note: Some offending log lines that appeared had the message `Too many open files`.

**Comment by fraenkel** [comment]
Just revert yet again to remove the timeouts. The DEA PR will handle the rest.

https://github.com/cloudfoundry/dea_ng/pull/172

**Comment by jpalermo** [comment]
Merged along with https://github.com/cloudfoundry/warden/issues/101

**Comment by jpalermo** [comment]
Merged
https://github.com/cloudfoundry/warden/commit/d9065ba9df3261517a2ababdb66ca22345d4b94d
