### ISSUE TITLE
Warden requests failures when requesting multiple containers

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/warden#104]
I am investigating the issue described [here](https://github.com/cloudfoundry/cf-release/issues/832#issuecomment-151871690), with this scenario on CF v215:

 * Given 1 running DEA,
 * if you scale one app (static html app, 64M mem, 10M disk) from 1 to 200 instances.
 * several instances will change state starting to crashed.
 * although eventually CF starts all the instances

Tracing the issue, I think the problem is on the DEA doing too many concurrent requests to the warden daemon. I simulated the issue with this script, which you can run on any runner. 

```
# /var/vcap/packages/warden/warden/warden_bomb.rb 

ENV['BUNDLE_GEMFILE'] ||= File.join(File.dirname(__FILE__), 'Gemfile')
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))

require "bundler"
Bundler.setup

require "warden/repl/repl_v2"

def run_something()
	repl = Warden::Repl::Repl.new(:socket_path => "/var/vcap/data/warden/warden.sock")
	handle=repl.process_line("create")[:result].strip.split(' ')[2]
	repl.process_line("run --handle #{handle} --script 'sleep 5; echo ok'")
end

threads = (1..100).map { 
	Thread.new{ run_something() }
}
threads.each { |t|
	begin
		t.join
	rescue Exception => e
		puts "Error #{e}"
		puts e.backtrace.join("\n")
	end
}
```

Run it in `/var/vcap/packages/warden/warden` with `/var/vcap/packages/ruby-2.1.6/bin/ruby myscript.rb`.

It requests 100 warden containers in parallel. Several request fail with errors:

```
Error command exited with failure
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden-client/lib/warden/client.rb:65:in `read'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden-client/lib/warden/client.rb:109:in `call'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden-client/lib/warden/client.rb:98:in `stream'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden/lib/warden/repl/repl_v2.rb:193:in `process_command'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden/lib/warden/repl/repl_v2.rb:116:in `process_line'
myscript.rb:13:in `run_something'
```

or 

```
Error Could not acquire network
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden-client/lib/warden/client.rb:65:in `read'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden-client/lib/warden/client.rb:109:in `call'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden/lib/warden/repl/repl_v2.rb:196:in `process_command'
/var/vcap/data/packages/warden/5f0154e5ba4baec289e1a05fe81ee1b9a5dc23e1.1-dfe472b24aff7b3c6fd2efc654c1a16b7194b9a6/warden/lib/warden/repl/repl_v2.rb:116:in `process_line'
myscript.rb:12:in `run_something'

```

## Questions

Although the issue is mitigated by the fact that CF platform will retry start the instances, I got some questions:

 * What are the limits of warden in this aspect?
 * How should it deal with this issue? shall we update the client library? should the client (dea_next) throttle the number of requests?

**Comment by Amit-PivotalLabs** [comment]
Hi @keymon 

Thanks for your investigation.  As you point out, the CF platform does retry starting the instances.  Has this issue caused problems for you in a production setting (i.e. outside of experimentation)?

Also, because the platform is migrating from the DEA/Warden/HM9k runtime to the new Diego (Rep/Garden/Auctioneer/Converger) runtime, we are less likely to address non-critical issues in Warden, and are validating performance and robustness of the new runtime.  Have you tried on Diego?

**Comment by keymon** [comment]
Hi @Amit-PivotalLabs, it makes sense what you say. 

Indeed we were investigating and doing performance tests of the CF platform. We were investigating the case and impact of tenants misbehaving/abusing the platform.

I understand the rationale of your prioritisation. Thank you a lot for the transparency and clarification about that! 

I will close the ticket, it will be here as a reference.

We will continue our investigations on Diego+Garden and let you know our findings.

Thank you
