### ISSUE TITLE
warden in docker container issue

### ISSUE THREAD

**Issue by WIZARD-CXY** [cloudfoundry/warden#65]
Hello , I am working on moving cloudfoundry dea into the docker container, only to find it failed due to some warden issue.So I spent some time debugging it,reading warden logs , only to find the below error message. I manually run the mkdir command in the docker  container ,there is no "Read-only file system" error.So I am really confused ,Please help   me,Thanks in advance. 
- mkdir -p /var/vcap/data/warden/depot/17pq7nnqcu9/mnt/dea_ng/buildpacks\n
  mkdir: cannot create directory `/var/vcap/data/warden/depot/17pq7nnqcu9/mnt/dea_ng': Read-only file system\n
  Process for \"./lib/hook-child-before-pivot.sh\" exited with 1\nwshd: wshd.c:679: child_run: Assertion`rv == 0' failed.\nError waiting for acknowledgement from child process\n"},"thread_id":19102880,"fiber_id":20042340,"process_id":4403,"file":"/warden/lib/warden/container/spawn.rb","lineno":135,"method":"set_deferred_success"}

**Comment by LaynePeng** [comment]
I met this issue, too. Anyone has update?
