### ISSUE TITLE
SIGCHLD is being blocked for child processes spawned by wshd

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/warden#85]
See details of issue and potential fix at https://groups.google.com/a/cloudfoundry.org/forum/?fromgroups#!topic/vcap-dev/NrlPuBQBkic.

This is likely also the root cause of issues reported at https://www.pivotaltracker.com/story/show/83352380 and http://support.run.pivotal.io/entries/70362955-spawning-node-child-processes-results-in-zombies.

Aaron Huber
Intel Corporation

**Comment by dieucao** [comment]
@amhuber We believe we have a fix for this for warden which we'll make available in the next cf-release.  We're hoping to publish that release early next week.
Story details https://www.pivotaltracker.com/story/show/83352380
Commit with the fix. https://github.com/cloudfoundry/warden/commit/dbde59424a6cdbeae3a265c1c8ce5a37f8f4ebae

**Comment by amhuber** [comment]
Looks perfect, thanks for jumping on this and we'll test it out as soon as the new release is available.

**Comment by goonzoid** [comment]
Hi @amhuber. It looks like this fix was released and is present in cf-release v196 and above. Did you get a chance to test whether or not this fixed your issue?

**Comment by amhuber** [comment]
My apologies, I tested this a while ago but forgot that this issue was still open.  The fix is indeed working correctly.
