### ISSUE TITLE
wshd crashed when it is creating a container

### ISSUE THREAD

**Issue by guanglinlv** [cloudfoundry/warden#86]
hi,

I got a trouble that <a href="https://github.com/cloudfoundry/cf-release/issues/664">wshd crash with centos-7.</a>

**Comment by goonzoid** [comment]
Closing for now as this seems to be being dealt with over at [https://github.com/cloudfoundry/cf-release/issues/664](cf-release).

Please re-open or create a new issue if the issue turns out to be isolated to warden.
