### ISSUE TITLE
Warden REPL v2 throwing out an error

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/warden#96]
Hi,

I just got this error today, it's really new. I have been running tests on Warden the past week without issue, this pops up all of a sudden. I rebuilt and setup Warden but to no avail, I still get this error while running `bundle exec bin/warden` with root privileges.

It seems that `.warden-history` is empty, could this be the reason?

Any advice?

```text
/root/warden/warden/lib/warden/repl/repl_v2.rb:279:in `block in restore_history': undefined method `map' for nil:NilClass (NoMethodError)
        from /root/warden/warden/lib/warden/repl/repl_v2.rb:277:in `open'
        from /root/warden/warden/lib/warden/repl/repl_v2.rb:277:in `restore_history'
        from /root/warden/warden/lib/warden/repl/repl_v2.rb:52:in `start'
        from /root/warden/warden/lib/warden/repl/repl_v2_runner.rb:84:in `run_interactively'
        from /root/warden/warden/lib/warden/repl/repl_v2_runner.rb:70:in `run'
        from bin/warden:11:in `<main>'

**Comment by jpalermo** [comment]
That looks like it might be the problem. Can you try removing .warden-history. It looks like the code assumes that if the file exists, it will have history content inside of it.

**Comment by kennetham** [comment]
Yup it works now. I have to look through the source code and found out that it's reading the .warden_history.

Thanks!
